//! Example for using the debug tracing functionality to sample the ray distribution in a simple
//! scene. This is mostly useful for verifying the physical correctness of new materials / shapes.

use cgmath::Vector3;
use grinray::{
    objects::{ObjectTransform, RTObject, Sphere}, CountingTracer, CountingTreeNode, LinearGRINFresnelMaterial, Material, Ray, TraceEvent, Tracer
};
use pyo3::{
    prelude::*,
    types::{PyList, PyTuple},
};
use rand::SeedableRng;
use rand_xoshiro::Xoshiro256Plus;

const PLOTTING_CODE: &str = include_str!("plot.py");
const PLOTTING_FUNC: &str = "plot";

fn main() {
    // Scene: unit sphere at (0,0) with linear gradient index in x direction
    // By using the debug tracer we can see that there is a lot of internal reflection in the
    // sphere which explains why some of rays appears to exit the sphere at "impossible" angles
    const SPHERE_RADIUS: f64 = 1.0;
    let sphere = Sphere::new(SPHERE_RADIUS);
    let sphere_transform = ObjectTransform::identity();
    let material = LinearGRINFresnelMaterial::new(1.4, Vector3::new(0.1, 0., 0.), 1.0);
    let mut tracer = CountingTracer::new();
    let mut rng = Xoshiro256Plus::from_seed([
        9, 41, 26, 176, 113, 164, 141, 6, 251, 27, 52, 143, 10, 196, 76, 147, 99, 215, 103, 223,
        78, 137, 249, 101, 252, 6, 139, 184, 69, 177, 191, 211,
    ]);
    // Spawn array of rays going into positive x direction in the xz-plane
    const NUM_RAYS: usize = 100;
    const SAMPLES_PER_RAY: usize = 50;
    const Z_MIN: f64 = -SPHERE_RADIUS * 1.1;
    const Z_MAX: f64 = SPHERE_RADIUS * 1.1;
    const DZ: f64 = (Z_MAX - Z_MIN) / (NUM_RAYS - 1) as f64;
    const RAY_MAXDEPTH: usize = 20;
    for i in 0..NUM_RAYS {
        let ray = Ray {
            start: Vector3::new(-2.0, 0., Z_MAX - i as f64 * DZ),
            dir: Vector3::unit_x(),
            depth: RAY_MAXDEPTH,
        };
        // Get the intersection of the ray and the sphere
        // Note: Since a sphere is convex, the outgoing ray cannot intersect with the sphere again
        // so we only need to do one intersection test per ray
        let intersection = sphere.intersect_ray(&sphere_transform, &ray);
        // Repeat the material interaction multiple times to get a statistically significant sample
        // of the ray distribution inside the sphere
        for _ in 0..SAMPLES_PER_RAY {
            let trace = tracer.new_trace(ray.start);
            let final_ray = match &intersection {
                Some(intersection) => material
                    .next_ray(&ray, intersection, &sphere, &sphere_transform, &mut rng, &mut tracer, trace)
                    .expect("Raytracing failed: recursion limit exceeded"),
                None => ray.clone(),
            };
            // Add an end point so that we can visualize the complete ray
            tracer.add_point(
                trace,
                grinray::TraceEvent::End,
                final_ray.start + final_ray.dir * 8. * SPHERE_RADIUS,
            );
            tracer.end_trace(trace);
        }
    }
    // -- Plotting (outsourced to Python / matplotlib) --
    Python::with_gil(|py| {
        // Convert traces to more Pythonic type
        let pytracetrees = PyList::empty_bound(py);
        let tracetrees = tracer.get_trace_trees();
        for tracetree in tracetrees {
            pytracetrees
                .append(tracetree_to_py(py, &tracetree))
                .unwrap();
        }
        // Load plotting code into module
        let module = PyModule::from_code_bound(py, PLOTTING_CODE, "", "")
            .expect("Failed to load plotting code into module");
        // Call plotting function
        let plotting_func = module
            .getattr(PLOTTING_FUNC)
            .expect("Failed to get handle to plotting function");
        plotting_func
            .call1((pytracetrees,))
            .expect("Failed to call plotting function");
    });
}

/// Mapping function of trace events to primitive numbers (for conversion to Python types)
fn traceevent_map(e: TraceEvent) -> u8 {
    match e {
        TraceEvent::Start => 0,
        TraceEvent::Intermediate => 1,
        TraceEvent::Reflection => 2,
        TraceEvent::Refraction => 3,
        TraceEvent::End => 4,
    }
}

/// Function to turn the Rusty tree structure generated by the debug tracer into nested Python lists
fn tracetree_to_py<'py>(py: Python<'py>, node: &CountingTreeNode) -> Bound<'py, PyList> {
    // Process child nodes
    let pychildren = PyList::empty_bound(py);
    for child in &node.children {
        pychildren.append(tracetree_to_py(py, child)).unwrap();
    }
    // PyO3 is a bit fussy when mixing Rust and Python types, so we add things piecewise
    let pynode = PyList::empty_bound(py);
    // Element 0: Location
    pynode
        .append(vec3_to_py(py, node.tracepoint.location))
        .unwrap();
    // Element 1: Event (as a number)
    pynode
        .append(traceevent_map(node.tracepoint.event))
        .unwrap();
    // Element 2: Ray count of node
    pynode.append(node.count).unwrap();
    // Element 3: Child nodes
    pynode.append(pychildren).unwrap();
    pynode
}

/// Conversion method from cgmath Vector3 to a Python tuple
fn vec3_to_py<'py>(py: Python<'py>, vec: Vector3<f64>) -> Bound<'py, PyTuple> {
    PyTuple::new_bound(py, [vec.x, vec.y, vec.z])
}
